In [2]:
import pandas as pd
import selenium
import time
from selenium import webdriver

import warnings
warnings.filterwarnings("ignore")

In [3]:
driver=webdriver.Chrome(r"C:\\Users\\p.c\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [3]:
driver.get("https://www.yatra.com/")

In [16]:
links=[]
for i in driver.find_elements_by_xpath("//ul[@class='destlist']/li")[:6]:
    i.click()
    try:
        links.extend([w.get_attribute('href') for w in driver.find_elements_by_xpath("//a[@class='VueCarousel-slide items']")[:-10]])
    except:
        continue

In [7]:
links=["https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BOM&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=GOI&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=BLR&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=DEL&originCountry=IN&destination=MAA&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BOM&originCountry=IN&destination=VNS&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BOM&originCountry=IN&destination=DEL&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BOM&originCountry=IN&destination=GOI&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BOM&originCountry=IN&destination=IXC&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BOM&originCountry=IN&destination=CCU&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BLR&originCountry=IN&destination=CCU&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BLR&originCountry=IN&destination=DEL&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BLR&originCountry=IN&destination=JAI&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BLR&originCountry=IN&destination=LKO&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=BLR&originCountry=IN&destination=GAU&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=HYD&originCountry=IN&destination=DEL&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=HYD&originCountry=IN&destination=MAA&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=HYD&originCountry=IN&destination=BLR&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=HYD&originCountry=IN&destination=GOI&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=CCU&originCountry=IN&destination=BLR&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=CCU&originCountry=IN&destination=BOM&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=CCU&originCountry=IN&destination=GAU&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=PNQ&originCountry=IN&destination=DEL&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=MAA&originCountry=IN&destination=DEL&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=PNQ&originCountry=IN&destination=CCU&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
       "https://flight.yatra.com/air-search-ui/seodom/trigger?type=O&viewName=normal&flexi=0&noOfSegments=1&origin=PAT&originCountry=IN&destination=BLR&preferred=&destinationCountry=IN&flight_depart_date=06%2F04%2F2022&ADT=1&CHD=0&INF=0&class=Economy&source=seo",
      ]

In [8]:
airline_name=[]
flightsDate=[]
departureTime=[]
arrivalTime=[]
Source=[]
Destination=[]
Duration=[]
Stops=[]
Price=[]

c=0
for i in links[::2]:
    driver.get(i)
    x=input("Got Link? (Y/N)")
    c+=1
    print("Link counter:",c)
    for j in range(9):
        print("\t\tStarted...")
        airline_name.extend([flightName.text for flightName in driver.find_elements_by_xpath("//span[@class='i-b text ellipsis']")])
        departureTime.extend([tim.text for tim in driver.find_elements_by_xpath("//div[@class='i-b pr']")])
        arrivalTime.extend([tim.text[:5] for tim in driver.find_elements_by_xpath("//p[@class='bold fs-15 mb-2 pr time']")])
        Source.extend([tim.text for tim in driver.find_elements_by_xpath("//p[@class='fs-10 font-lightgrey no-wrap city ellipsis']")[::2]])
        Destination.extend([tim.text for tim in driver.find_elements_by_xpath("//p[@class='fs-10 font-lightgrey no-wrap city ellipsis']")[1::2]])  
        Duration.extend([tim.text for tim in driver.find_elements_by_xpath("//p[@class='fs-12 bold du mb-2']")])
        Stops.extend([tim.text.split(" ")[0] for tim in driver.find_elements_by_xpath("//div[@class='stop-cont pl-13']/div/span")])
        Price.extend([tim.text.replace(",","") for tim in driver.find_elements_by_xpath("//div[@class='i-b tipsy fare-summary-tooltip fs-18']")])
        date=driver.find_element_by_xpath("//div[@class='day-li text-center cursor-pointer pr active font-primary-color']").text
        for k in range(len(driver.find_elements_by_xpath("//div[@class='tuple']"))):
            flightsDate.append(date)
        
        print("\tChange Date counter:",j)
        if j in [2,5]:
            time.sleep(10)
        elif j==8:
            continue
        else:
            time.sleep(3)

Got Link? (Y/N)
Link counter: 1
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 2
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 3
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 4
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 5
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 6
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 7
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 8
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 9
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 10
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 11
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 12
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8
Got Link? (Y/N)
Link counter: 13
		Started...
	Change Date counter: 0
		Started...
	Change Date counter: 1
		Started...
	Change Date counter: 2
		Started...
	Change Date counter: 3
		Started...
	Change Date counter: 4
		Started...
	Change Date counter: 5
		Started...
	Change Date counter: 6
		Started...
	Change Date counter: 7
		Started...
	Change Date counter: 8

In [16]:
len(DOJ)

717

In [23]:
flightsDate[0].split("\n")[0].split(",")[1][1:]

'Wed, 6 Apr\n7,320'

In [38]:
import pandas as pd

df=pd.DataFrame()


df['AirlineName']=airline_name
df['Date']=flightsDate
df['Source']=Source
df['Destination']=Destination
df['DepartureTime']=departureTime
df['ArrivalTime']=arrivalTime
df['Duration']=Duration
df['Total_Stops']=Stops
df['Price']=Price
df

,AirlineName,Date,Source,Destination,DepartureTime,ArrivalTime,Duration,Total_Stops,Price
0,SpiceJet,"Wed, 6 Apr\n7,320",New Delhi,Mumbai,07:20,09:35,2h 15m,Non,7318
1,SpiceJet,"Wed, 6 Apr\n7,320",New Delhi,Mumbai,18:55,21:10,2h 15m,Non,7318
2,SpiceJet,"Wed, 6 Apr\n7,320",New Delhi,Mumbai,19:45,22:00,2h 15m,Non,7318
3,SpiceJet,"Wed, 6 Apr\n7,320",New Delhi,Mumbai,06:20,08:45,2h 25m,Non,7318
4,SpiceJet,"Wed, 6 Apr\n7,320",New Delhi,Mumbai,05:45,17:50,12h 05m,1,7318
...,...,...,...,...,...,...,...,...,...
2551,Air India,"Fri, 22 Apr\n5,411",Patna,Bangalore,16:00,11:10,19h 10m,2,14232
2552,Vistara,"Fri, 22 Apr\n5,411",Patna,Bangalore,10:00,19:15,9h 15m,2,15387
2553,Vistara,"Fri, 22 Apr\n5,411",Patna,Bangalore,10:00,19:15,9h 15m,2,15387
2554,Vistara,"Fri, 22 Apr\n5,411",Patna,Bangalore,10:00,20:55,10h 55m,2,15387
2555,Vistara,"Fri, 22 Apr\n5,411",Patna,Bangalore,10:00,17:45,7h 45m,2,15912

In [27]:
driver.close()

In [59]:
import numpy as np
date_null=list(np.where(df['Date']==''))[0]

In [66]:
for i in date_null:
    df.drop(i,inplace=True)

In [67]:
df.shape

(2374, 9)

In [69]:
for i in range(2374):
    df['Date'].iloc[i]=str(df['Date'].iloc[i]).split("\n")[0].split(",")[1][1:] +" 2022"

In [70]:
df['Date'].value_counts()

15 Apr 2022    461
22 Apr 2022    448
6 Apr 2022     274
18 Apr 2022    254
21 Apr 2022    199
23 Apr 2022    140
16 Apr 2022    129
17 Apr 2022     75
28 Apr 2022     75
19 Apr 2022     72
26 Apr 2022     67
11 Apr 2022     64
24 Apr 2022     61
14 Apr 2022     55
Name: Date, dtype: int64

In [72]:
df.drop_duplicates(inplace=True)

In [74]:
df.to_excel("Flight_scrapped_data.xlsx")